meta_product_name: "Africarriers Ltd"
meta_title: "Africarriers Ltd - We Drive Africa"
meta_description: "East Africa's biggest autombile dealer. Specialising in commercial & retail vehicles."
meta_image: "cover.png" # should exist in `app/assets/images/`
